In [8]:
import numpy as np

In [ ]:
# Create a numpy array
arr = np.array([1,2,3,4,5])


print(arr)

# Numpy array is called 'ndarray'
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#create array from tuple
arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


# Dimentional Array (Nested Array)

In [18]:
# 0-D Array
arr = np.array(42)

print(arr)

42


In [19]:
# 1-D Array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [20]:

# 2-D Array 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
# 3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
# Check how many dimentions the array have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Specify how many dimentions can the array have via ndmin
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Array Indexing

In [ ]:
arr = np.array([1,2,3,4])

print(arr[0])

1


In [ ]:
# Access 2-D array
arr = np.array([[1,2,3],[4,5,6]])

print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  5


In [28]:
# Access 3-D Array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0, 1, 2])

6


In [29]:
# Negetive indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


## ARRAY SLICING

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

# NEGETIVE SLICING
print(arr[-3:-1])

#STEP
# Used o determine the step of the slicing
print(arr[1:5:2])

# Return every other element from the entire array
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 4 7]


In [44]:
# SLICING 2-D ARRAY

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4])
print(arr[0:2, 1:4])


[7 8 9]
[[2 3 4]
 [7 8 9]]
