In [8]:
import numpy as np

In [ ]:
# Create a numpy array
arr = np.array([1,2,3,4,5])


print(arr)

# Numpy array is called 'ndarray'
print(type(arr))


[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#create array from tuple
arr = np.array((1,2,3,4,5))

print(arr)

[1 2 3 4 5]


# Dimentional Array (Nested Array)

In [18]:
# 0-D Array
arr = np.array(42)

print(arr)

42


In [19]:
# 1-D Array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [20]:

# 2-D Array 
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [21]:
# 3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [22]:
# Check how many dimentions the array have
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
# Specify how many dimentions can the array have via ndmin
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


## Array Indexing

In [ ]:
arr = np.array([1,2,3,4])

print(arr[0])

1


In [ ]:
# Access 2-D array
arr = np.array([[1,2,3],[4,5,6]])

print('2nd element on 1st row: ', arr[0, 1]) 

2nd element on 1st row:  5


In [28]:
# Access 3-D Array
arr = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr[0, 1, 2])

6


In [29]:
# Negetive indexing

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])


Last element from 2nd dim:  10


## ARRAY SLICING

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])
print(arr[4:])
print(arr[:4])

# NEGETIVE SLICING
print(arr[-3:-1])

#STEP
# Used o determine the step of the slicing
print(arr[1:5:2])

# Return every other element from the entire array
print(arr[::2])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 4 7]


In [44]:
# SLICING 2-D ARRAY

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1,1:4])
print(arr[0:2, 1:4])


[7 8 9]
[[2 3 4]
 [7 8 9]]


## DATATYPES 

In [ ]:
#CHECK DATA TYPE
arr = np.array([1, 2, 3, 4])
print(arr.dtype)


arr = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

int64
<U6


In [48]:
# CREATE ARRAY WITH A DEFINED DATA TYPE

arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [54]:
# CREATE AN ARRAY WITH DATA TYPE 4 BYTES INTEGET

arr = np.array([1,2,3,4,5],dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [55]:
# DATA TYPE CONVERSION

arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)

[1 2 3]
int32


In [56]:
# DATA TYPE CONVERSION (BOOLEAN)

arr = np.array([1.1,2.1,3.1])

newarr = arr.astype('bool')

print(newarr)
print(newarr.dtype)

[ True  True  True]
bool


## ARRAY COPY & VIEW

In [57]:
#MAKE COPY, CHANGE ORIGINAL ARRAY, AND DISPLAY BOTH

arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 6

print(arr)
print(x)

[6 2 3 4 5]
[1 2 3 4 5]


In [58]:
#MAKE VIEW, CHANGE ORIGINAL, AND DISPLAY BOTH

arr = np.array([1,2,3,4,5])
x = arr.view()
arr[0] = 6

print(arr)
print(x)

[6 2 3 4 5]
[6 2 3 4 5]


In [59]:
#MAKE VIEW, CHANGE VIEW, AND DISPLAY BOTH

arr = np.array([1,2,3,4,5])
x = arr.view()
x[0] = 6

print(arr)
print(x)

[6 2 3 4 5]
[6 2 3 4 5]


In [60]:
#CHECK IF ARRAY OWNS ITS DATA OR NOT

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


## ARRAY SHAPE

In [ ]:
# GET THE SHAPE OF AN ARRAY

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape) 
# first number represents dimention & secound one elements

(2, 4)


In [62]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


## ARRAY RESHAPING

In [ ]:
#CONVERT 1-D ARRAY INTO 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4,3) # 4 = dimention, 3 = element count

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [64]:
# CONVERT 1-D ARRAY INTO 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [ ]:
# CHECK IF RETURN TYPE IS COPY OR ViWEW
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)
# IT RETURNS THE ORIGINAL ARRAY SO IT IS A VIEW

[1 2 3 4 5 6 7 8]


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [73]:
#FLATTENING THE ARRAY 
#CONVERT A MULTIDIMENSIONAL ARRAY INTO A 1D ARRAy

arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


## ITERATING ARRAY

In [ ]:
#ITERATING 1-D ARRAY
arr = np.array([1,2,3])

for x in arr:
    print(x)

1
2
3


In [75]:
#ITERATING 2-D ARRAY
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [77]:
#ITERATING 2-D ARRAY - EACH ELEMENT
arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [78]:
# ITERATING ARRAYS USING nditer()

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
    print(x)

1
2
3
4
5
6
7
8


In [ ]:
# CHANGE DATAYPE WHILE ITERATING
arr = np.array([1, 2, 3])

#NumPy does not change the data type of the element in-place 
#(where the element is in array) so it needs some other space 
# to perform this action, that extra space is called buffer, 
# and in order to enable it in nditer() we pass flags=['buffered'].


for x in np.nditer(arr,flags=['buffered'],op_dtypes=['S']):
    print(x)

np.bytes_(b'1')
np.bytes_(b'2')
np.bytes_(b'3')


In [ ]:
#ITERATING WITH DIFFERENT STEP SIZE
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

#Iterate through every scalar element of the 2D array 
# skipping 1 element:


for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [81]:
# ENAMERATE ON 1D ARRAYS ELEMENT

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [82]:
# ENAMERATE ON 1D ARRAYS ELEMENT

arr = np.array([[1, 2, 3],[4,5,6]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(1, 0) 4
(1, 1) 5
(1, 2) 6
