# Random Numbers in NumPy

## What is a random number?
Random number does NOT mean a different number every time. Random means something that can not be predicted logically.

## Pseudo Random and True Random.
Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called pseudo random.

Can we make truly random numbers?

Yes. In order to generate a truly random number on our computers we need to get the random data from some outside source. This outside source is generally our keystrokes, mouse movements, data on network etc.

We do not need truly random numbers, unless it is related to security (e.g. encryption keys) or the basis of application is the randomness (e.g. Digital roulette wheels).

NumPy offers the `random` module to work with random numbers

In [24]:
from numpy import random

In [25]:
# returns a true random number
x = random.randint(100)
print(x)

19


In [26]:
# genreate random float
x = random.rand()
print(x)

0.7102340645071697


In [27]:
# generate random 1-D array
x = random.randint(100,size=(5))
print(x)

[40 76 26 56 74]


In [28]:
# generate random 2-D array
x = random.randint(100, size=(3,5)) # 3 row, 5 elements
print(x)

[[32 11 46 84 60]
 [49 15 42 38 17]
 [21 84 47 65 77]]


In [29]:
# genrate 1-D array containing 5 random floats
x = random.rand(5)
print(x)

[0.64565002 0.94734518 0.22203523 0.40959745 0.78385094]


## Generate random number from array
The `choice` method allows you to generate a random value based on an array of values.

it takes an array as a parameter and randomly returns one of the values

In [ ]:
# returns one of the value from the
x = random.choice([3, 5, 7, 9])
print(x)

3


In [31]:
#Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):
x = random.choice([3,5,7,9],size=(3,5))
print(x)


[[5 7 3 3 3]
 [3 7 9 9 3]
 [7 9 9 7 3]]
