In [1]:
import numpy as np

## Array Broadcasting
It is a type of operation in numpy which allows to do arithmatic operations on numpy arrays

Broadcasting have specific rules to find weather two array can be aligned for operations or not that are:

- **Check Dimensions:** Ensure both array have same number of dimentions or expandable
- **Dimention Padding:** If array have different numbers of dimentions the smaller array is left-padded with one
- **Shape Compatibility:** Two dimentions are compatible if they are equal or one of them is 1

### Ex 1: Broadcasting a scaler to a 1D Array

In [2]:
arr = np.array([1,2,3])
res = arr + 1
print(res)

[2 3 4]


### Ex 2: Broadcasting a 1D array to a 2D Array

In [3]:
a = np.array([2, 4, 6])
b = np.array([[1, 3, 5], [7, 9, 11]])

res = a+b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


### Ex 3: Broadcasting in Conditional Operations

In [4]:
a = np.array([12, 24, 35, 45, 60, 72])
b = np.array(["Adult", "Minor"])

res = np.where(a>10,b[0],b[1])
print(res)

['Adult' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


### Ex 4: Using Broadcasting for Matrix Multiplication

In [5]:
m = np.array([[1, 2], [3, 4]])
v = np.array([10, 20])

res = m*v
print(res)

[[10 40]
 [30 80]]


### Ex 5: Scaling Data with Broadcasting
Consider a real-world scenario where we need to calculate the total calories in foods based on the amount of fats, proteins and carbohydrates. Each nutrient has a specific caloric value per gram.

- **Fats:** 9 calories per gram (CPG)
- **Proteins:** 4 CPG
- **Carbohydrates:** 4 CPG


![Scaling Data with Broadcasting](https://media.geeksforgeeks.org/wp-content/uploads/20251205165826062052/chart.webp)

Left table shows the original data with food items and their respective grams of fats, proteins and carbs. The array [9, 4, 4] represents the caloric values per gram for fats, proteins and carbs respectively. This array is being broadcast to match the dimensions of the original data and arrow indicates the broadcasting operation.

- Broadcasting array is multiplied element-wise with each row of the original data.
- As a result right table shows the result of the multiplication where each cell represents the caloric contribution of that specific nutrient in the food item.

In [6]:
fd = np.array([ [0.8, 2.9, 3.9],
                [52.4, 23.6, 36.5],
                [55.2, 31.7, 23.9],
                [14.4, 11.0, 4.9] ])

cpg = np.array([9, 4, 4])
res = fd * cpg
print(res)

[[  7.2  11.6  15.6]
 [471.6  94.4 146. ]
 [496.8 126.8  95.6]
 [129.6  44.   19.6]]


### Adjusting Temperature Data Across Multiple Locations
Suppose you have a 2D array representing daily temperature readings across multiple cities and you want to apply a correction factor to each city’s temperature data.

In [ ]:
temp = np.array([ [30, 32, 34, 33, 31],
                  [25, 27, 29, 28, 26],
                  [20, 22, 24, 23, 21] ])

corr = np.array([1.5, -0.5, 2.0])
res = temp + corr[:, None]
print(res)

[[31.5 33.5 35.5 34.5 32.5]
 [24.5 26.5 28.5 27.5 25.5]
 [22.  24.  26.  25.  23. ]]


Explanation:

- corr[:, None] turns the 1D array into a column vector.
- NumPy broadcasts this vector down each row of temp.
- Each city’s temperatures get adjusted using its corresponding correction factor.


### Ex 7: Normalizing Image Data
Normalization is important in many real-world scenarios like image processing and machine learning because it:

- Centers data by subtracting the mean by ensuring features have zero mean.
- Scales data by dividing by the standard deviation by ensuring features have unit variance.
- Improves numerical stability and performance of algorithms like gradient descent.


In [15]:
img = np.array([ [100, 120, 130],
                 [90, 110, 140],
                 [80, 100, 120] ])

m = img.mean(axis=0)
s = img.std(axis=0)
res = (img - m) / s
print(res)

[[ 1.22474487  1.22474487  0.        ]
 [ 0.          0.          1.22474487]
 [-1.22474487 -1.22474487 -1.22474487]]


- m and s are 1D arrays (mean and std for each column).
- NumPy broadcasts them across all rows of img.
- (img - m) centers the data.
- Dividing by s scales it, giving the normalized values.


 ### Ex 8: Centering Data in Machine Learning
 Centering data is an important step in many machine learning workflows. Broadcasting helps center the data efficiently by subtracting the mean from each feature. This example centers each feature by subtracting its mean using NumPy broadcasting.


In [18]:
data = np.array([ [10, 20],
                  [15, 25],
                  [20, 30] ])

m = data.mean(axis=0)
res = data - m
print(res)

[[-5. -5.]
 [ 0.  0.]
 [ 5.  5.]]


- m is a 1D array containing the mean of each column.
- NumPy broadcasts m across all rows.
- Subtracting it centers every feature around zero.
