## numpy.dot() in Python
numpy.dot() is used to compute the dot product of two arrays.

- For 1D arrays, it returns the scalar dot product.
- For 2D arrays, it performs matrix multiplication.
- For arrays with N dimensions, it performs a sum-product over the last axis of the first array and the second-to-last axis of the second array.

In [1]:
import numpy as np

In [2]:
# This example shows how numpy.dot() calculates the dot product of two 1D arrays.

a = np.array([2, 3])
b = np.array([4, 5])
print(np.dot(a,b))

23


`Explanation: np.dot(a, b) -> 2*4 + 3*5 = 8 + 15 = 23.`

#### Syntax
```py
numpy.dot(a, b, out=None)
```

**Parameters:**

- a: First input array.
- b: Second input array.
- out (Optional): array to store the result.


## Examples

**Example 1:** This example demonstrates the dot product of two complex numbers using numpy.dot().

In [3]:
a = 2 + 3j
b = 4 + 5j
print(np.dot(a, b))

(-7+22j)


`Explanation: np.dot(a, b) multiplies using complex arithmetic -> 2*(4+5j) + 3j*(4+5j) -> -7 + 22j.`

**Example 2:** This example shows matrix multiplication using numpy.dot() on two 2D arrays.

In [4]:
a = np.array([[1, 4],
              [5, 6]])

b = np.array([[2, 4],
              [5, 2]])

print(np.dot(a, b))

[[22 12]
 [40 32]]


**Explanation:** np.dot(a, b) performs matrix multiplication

- For output [0,0] -> (1×2) + (4×5) = 2 + 20 = 22
- For output [0,1] -> (1×4) + (4×2) = 4 + 8 = 12
- For output [1,0] -> (5×2) + (6×5) = 10 + 30 = 40
- For output [1,1] -> (5×4) + (6×2) = 20 + 12 = 32

**Example 3:** This example uses numpy.dot() with a 2D array and a 1D array to produce a vector.

In [5]:
a = np.array([[3, 5],
              [1, 2],
              [4, 1]])

b = np.array([2, 3])

print(np.dot(a, b))

[21  8 11]


**Explanation:** Each row of a is dotted with vector b

- Row 1 -> 3×2 + 5×3 = 6 + 15 = 21
- Row 2 -> 1×2 + 2×3 = 2 + 6 = 8
- Row 3 -> 4×2 + 1×3 = 8 + 3 = 11


## Matrix Multiplication 
NumPy provides a way to compute matrix multiplication using `numpy.dot()` function. This method calculates dot product of two arrays, which is equivalent to matrix multiplication.

In [7]:
a = [[1, 2], [2, 3]]
b = [[4, 5], [6, 7]]

print("Matrix A:")
print(a)
print("Matrix B:")
print(b)

c = np.dot(a,b)
print("Result:")
print(c)

Matrix A:
[[1, 2], [2, 3]]
Matrix B:
[[4, 5], [6, 7]]
Result:
[[16 19]
 [26 31]]


In [8]:
x = [[1, 2], [2, 3], [4, 5]]
y = [[4, 5, 1], [6, 7, 2]]

print("Matrix X:")
print(x)
print("Matrix Y:")
print(y)

z = np.dot(x, y)
print("Result:")
print(z)

Matrix X:
[[1, 2], [2, 3], [4, 5]]
Matrix Y:
[[4, 5, 1], [6, 7, 2]]
Result:
[[16 19  5]
 [26 31  8]
 [46 55 14]]
